# 1 Program  =  Instructions for computers.

# Vocabulary




# 2 Programing languages = Diffrent ways we can write and  Provide Instructions to computers.
# 3 SYNTAX = THE FORMATIING RULE OF A LANGUAGE , IN THIS CASE , A PROGRAMMING LANGUAGE.

# ADDTIONAL NOTE - WHEN WE ARE WRITING PROGRAMS , ALL WE ARE DOING IS TALKING TO THE COMPUTER GIVING IT INSTRUCTIONS TO COMPLETE A TASK.

# A COMPUTER PROGRAM iS A SET OF iNSTRUCTIONS THAT A COMPUTER CAN EXUCUTE iN  ORDER TO PERFORM A SPECIFIC TASK OR ACHIEVE A PARTICULAR GOAL.
# PYTHON iS A FUNCTION PROGRAM LANGUAGE.

# STRING - ALLOW PROGRAMMERS TO WRITE iSLOATED PROGRAMS CHARCATERS THAT WONT iMPACT THE PROGRAMS ; SUCH AS WORDS.

# INTERGERS - A WHOLE NUMBER ; NON DECIMAL NUMBER.

# FLOAT - A DECIMAL NUMBER.

# BOOLEAN - A TRUE OR FALSE.

# PRINT() - A FUNCTION THAT PRINTS THE VALUE YOU PROVIDE TO IT.

# INPUT() - A FUNCTION THAT TAKES IN THAT VALUE YOU PROVIDE TO IT.


def myFunction():
    print( " Here are nmy Instructions...")

    # How to write a function In JavaScript
    Function myFunction(data)
    Consol.log( " Here are my Instructions...")

    