# THREE PARAGRAPH PITCH.


# My Program Design will be an Alarm Clock. What I am trying to solve of this Alarm clock Is to that the alarm Clock goes off Specifically when Its time for you to walk your dog , the time set for you to walking your dog would be around 5:30.
# I am desigining my program for myself because I have trouble finding out a Specific time to walk the dog. I convey this because I have various times when I choose to walk the dog , one day I might walk her at 6:45 before school or maybe on the weekend probably around one. 
# I specifcally say 5:30 because its a good time. And I say this Is a good time because in school we get out at 3:15 so by time I might get home will maybe be around 4:00 and if Im tired otr need to do my homework from school I may want to rest or something , this why I say 5:30 should be the specifc set time from my program to go off.


# One , What Problems am I trying to solve In my Program? The Problem that I am trying to solve Is getting up to walk my dog at a SPECIFIC time. Why , you might ask because I want her to go to the bathroom outside and start to get used to going to the bathroom outside.
# Two , What tools and reasech can I use to solve this? Any tools or reaserch I can use to solve this Is that I can look on Youtube and maybe search up something that could possibly help me configure my program.

# I feel this type of program that Im trying to create will really help me. I say this because it will help me do what I significally need to do on time and faster.
# And Maybe get other things done.

